spring:
  application:
    name: EnglishWithMe-API
  
  datasource:
    url: jdbc:mysql://localhost:3306/englishwithme
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    com.englishwithme: DEBUG
